export enum InstanceStatus {
  UNKNOWN = 'UNKNOWN',
  BUILDING = 'BUILDING',
  STARTING = 'STARTING',
  ACTIVE = 'ACTIVE',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  REBOOTING = 'REBOOTING',
  UNAVAILABLE = 'UNAVAILABLE',
  ERROR = 'ERROR',
  DELETING = 'DELETING',
  DELETED = 'DELETED'
}
